services:
  proxy:
    image: ghcr.io/linuxfight/deepseek4free:main
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 5s
      retries: 3
    restart: always